spring.application.name=enterprise-ai-support-assistant

server.port=8080

####################################
# Ollama Configuration
####################################

spring.ai.ollama.base-url=http://localhost:11434

#spring.ai.ollama.chat.options.model=qwen3:4b
#spring.ai.ollama.chat.options.model=gemma3:4b
#spring.ai.ollama.chat.options.model=qwen2.5:3b
spring.ai.ollama.chat.options.model=qwen2.5:7b

spring.ai.ollama.embedding.options.model=nomic-embed-text

spring.ai.vectorstore.chroma.client.url=http://localhost:8000
#spring.ai.vectorstore.chroma.client.port=8000

spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.chat.options.top-k=20
spring.ai.ollama.chat.options.top-p=0.8
spring.ai.ollama.chat.options.num-predict=300

####################################
# Logging
####################################

logging.level.org.springframework.ai=INFO

logging.level.com.tpms.ai=DEBUG

#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html

########################
# H2 Database
########################

#spring.datasource.url=jdbc:h2:mem:tpmsdb

#spring.datasource.driverClassName=org.h2.Driver

#spring.datasource.username=sa

#spring.datasource.password=

#spring.h2.console.enabled=true

#spring.h2.console.path=/h2-console

#spring.sql.init.mode=always

########################
# SQL Server
########################

spring.datasource.url=jdbc:sqlserver://localhost:59178;databaseName=ENTERPRISE_AI_DB;encrypt=true;trustServerCertificate=true
#spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=ENTERPRISE_AI_DB;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa

spring.datasource.password=Kolkata@26

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

####################################
# ITSM Provider
####################################

itsm.provider=GLPI

####################################
# GLPI
####################################

glpi.base-url=http://localhost/glpi/apirest.php
glpi.app-token=BFYveuBkAWDqb1fgH1ubQ8u3HYrbx2WegUvmS57J
glpi.user-token=yll8vnQNXTvWNcWw2dhIaAEIhWQwGqD9KhLloXxv

####################################
# flyway
####################################

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration